services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: train-booking-backend

    restart: unless-stopped

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
