"""initial database schema

Revision ID: 6f19d2026e4c
Revises: 
Create Date: 2026-08-03 02:16:43.056516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f19d2026e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('distance_from_start_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('distance_from_start_km >= 0', name='ck_station_distance_non_negative'),
    sa.CheckConstraint('order_index >= 0', name='ck_station_order_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('boarding_minutes_before', sa.Integer(), server_default='30', nullable=False),
    sa.Column('turnaround_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.CheckConstraint('boarding_minutes_before >= 0', name='ck_train_boarding_minutes_non_negative'),
    sa.CheckConstraint('turnaround_minutes >= 0', name='ck_train_turnaround_minutes_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.Integer(), nullable=False),
    sa.Column('coach_type', sa.Enum('RESERVED', 'UNRESERVED', name='coach_type'), nullable=False),
    sa.CheckConstraint('coach_number > 0', name='ck_coach_number_positive'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'coach_number', name='uq_coach_train_number')
    )
    op.create_index(op.f('ix_coaches_train_id'), 'coaches', ['train_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('start_station_id', sa.Integer(), nullable=False),
    sa.Column('end_station_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.Enum('FORWARD', 'REVERSE', name='trip_direction'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False),
    sa.CheckConstraint('arrival_time > departure_time', name='ck_trip_arrival_after_departure'),
    sa.CheckConstraint('start_station_id <> end_station_id', name='ck_trip_different_terminal_stations'),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'departure_time', name='uq_train_departure_time')
    )
    op.create_index('ix_trip_search', 'trips', ['status', 'direction', 'departure_time'], unique=False)
    op.create_index(op.f('ix_trips_departure_time'), 'trips', ['departure_time'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_train_id'), 'trips', ['train_id'], unique=False)
    op.create_index('uq_one_scheduled_trip_per_train', 'trips', ['train_id'], unique=True, postgresql_where=sa.text("status = 'SCHEDULED'::trip_status"))
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'seat_number', name='uq_seat_coach_number')
    )
    op.create_index(op.f('ix_seats_coach_id'), 'seats', ['coach_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('origin_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(length=150), nullable=False),
    sa.Column('passenger_email', sa.String(length=255), nullable=True),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (status = 'CONFIRMED' AND cancelled_at IS NULL)\n            OR\n            (status = 'CANCELLED' AND cancelled_at IS NOT NULL)\n            ", name='ck_booking_cancelled_timestamp'),
    sa.CheckConstraint('fare >= 0', name='ck_booking_fare_non_negative'),
    sa.CheckConstraint('origin_station_id <> destination_station_id', name='ck_booking_different_stations'),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_booking_overlap_search', 'bookings', ['trip_id', 'seat_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_seat_id'), 'bookings', ['seat_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_trip_id'), 'bookings', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_trip_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_seat_id'), table_name='bookings')
    op.drop_index('ix_booking_overlap_search', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_seats_coach_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index('uq_one_scheduled_trip_per_train', table_name='trips', postgresql_where=sa.text("status = 'SCHEDULED'::trip_status"))
    op.drop_index(op.f('ix_trips_train_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_time'), table_name='trips')
    op.drop_index('ix_trip_search', table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_coaches_train_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_table('trains')
    op.drop_table('stations')
    # ### end Alembic commands ###
